package net.packet;

/**
 * This packet is sent by the client when it wants to send a file to
 * another client. The net.server stores this packet and will send it back to the
 * requested client if they accept. UID generated by the net.server.
 *
 * This packet is also sent from the net.server to the client when it has accepted
 * the file.
 *
 * @author Jacob Gordon
 * @version 1.0
 * @date 6/22/19
 **/
public class FileSendPacket {
    public String pin;
    public Byte[] content;
    public Byte[] contentParams;
    public Byte[] fileName, fileNameParams;
    public Byte[] fileSize, fileSizeParams;
    public String fileUID;
    public String senderUID; //assigned by server
    public Boolean isZip;

}
